kind: pipeline
type: kubernetes
name: default

steps:
  - name: show-promote-value-test
    image: alpine
    commands:
      - echo "This is a test again"
      - exit 1
trigger:
  event:
    - promote
    - push
